import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#fbfaf7',
  '--slot4-page-text': '#282f48',
  '--slot4-panel-bg': '#fff3f0',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#626a7f',
  '--slot4-soft-muted-text': '#8b91a2',
  '--slot4-accent': '#e94a1f',
  '--slot4-accent-fill': '#e94a1f',
  '--slot4-accent-soft': '#fff3f0',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#282f48',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#f1f7fe',
  '--slot4-cream': '#fbfaf7',
  '--slot4-warm': '#fff3f0',
  '--slot4-lavender': '#f1f7fe',
  '--slot4-gray': '#ecfaf0',
  '--slot4-pastel-blue': '#f1f7fe',
  '--slot4-pastel-green': '#ecfaf0',
  '--slot4-pastel-peach': '#fff3f0',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#fbfaf7',
  '--editable-page-text': '#282f48',
  '--editable-container': '1328px',
  '--editable-narrow': '830px',
  '--editable-border': '#282f481a',
  '--editable-nav-bg': '#fbfaf7',
  '--editable-nav-text': '#282f48',
  '--editable-nav-active': '#e94a1f',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#e94a1f',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#282f48',
  '--editable-footer-text': '#ffffff',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/15',
  shadow: 'shadow-[0_18px_60px_rgba(40,47,72,0.08)]',
  shadowStrong: 'shadow-[0_30px_80px_rgba(40,47,72,0.16)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(40,47,72,0.02),rgba(40,47,72,0.76))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-5 sm:px-8 lg:px-10',
    narrow: 'mx-auto w-full max-w-[var(--editable-narrow)] px-5 sm:px-8',
    bleed: 'w-full',
    sectionY: 'py-20 sm:py-24 lg:py-28',
  },
  grid: {
    halves: 'grid gap-10 lg:grid-cols-2',
    hero: 'grid gap-10 lg:grid-cols-[1fr_.75fr] lg:items-center',
    feature: 'grid gap-10 lg:grid-cols-[1fr_.66fr] lg:items-start',
    offset: 'grid gap-5 lg:grid-cols-[1fr_.5fr_1fr]',
    index: 'grid gap-3 lg:grid-cols-[1fr_1fr_1fr_2fr]',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[280px] shrink-0 snap-start sm:w-[340px]',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-10 lg:grid-cols-[1fr_.66fr] lg:items-start',
    heroGrid: 'grid gap-10 lg:grid-cols-[1fr_.75fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[280px] shrink-0 snap-start sm:w-[340px]',
  },
  type: {
    eyebrow: 'editable-label text-[11px] font-bold text-[var(--slot4-accent)]',
    heroTitle: 'editable-display text-[var(--editable-h1)] font-medium leading-none',
    sectionTitle: 'editable-display text-[var(--editable-h2)] font-medium leading-[1.04]',
    body: 'text-base leading-8 text-[var(--slot4-muted-text)] sm:text-lg',
    emphasis: 'editable-display italic text-[var(--slot4-accent)]',
    display: 'editable-display text-[var(--editable-h0)] font-medium leading-none',
  },
  surface: {
    card: `rounded-[28px] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[28px] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[28px] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
    panel: 'rounded-[28px] border border-[var(--editable-border)] bg-[var(--slot4-pastel-blue)]',
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-[200px] bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-200 hover:bg-[var(--slot4-dark-bg)]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-[200px] border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-bold text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-[200px] ${editablePalette.accentBg} px-6 py-3 text-sm font-bold text-[var(--slot4-on-accent)] transition duration-200 hover:bg-[var(--slot4-dark-bg)]`,
    ghost: 'inline-flex items-center justify-center gap-2 rounded-[200px] px-5 py-3 text-sm font-bold text-[var(--slot4-page-text)] transition duration-200 hover:text-[var(--slot4-accent)]',
  },
  badge: {
    pill: 'rounded-[200px] border border-[var(--editable-border)] bg-white px-3.5 py-1.5 text-xs font-semibold text-[var(--slot4-muted-text)]',
    accentPill: 'rounded-[200px] bg-[var(--slot4-accent-soft)] px-3.5 py-1.5 text-xs font-bold text-[var(--slot4-accent)]',
    metaChip: 'editable-label rounded-[200px] border border-[var(--editable-border)] px-3 py-1 text-[10px] text-[var(--slot4-muted-text)]',
  },
  media: {
    frame: `relative overflow-hidden rounded-[28px] ${editablePalette.mediaBg}`,
    frameFull: `relative overflow-hidden rounded-[28px] ${editablePalette.mediaBg}`,
    frameTall: `relative overflow-hidden rounded-[28px] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1 hover:shadow-[0_28px_70px_rgba(40,47,72,0.14)]',
    fade: 'transition duration-300 hover:opacity-80',
    zoom: 'transition duration-500 group-hover:scale-[1.035]',
    arrow: 'transition duration-300 group-hover:translate-x-1',
  },
} as const

export const aiLayoutRules = [
  'Map reference tokens into editableRootStyle first; downstream UI must consume CSS variables.',
  'Use Heyday-like asymmetric sections: split hero, offset panels, full-bleed bands, process numerals, and rails.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
